In [ ]:
# 설치된 라이브러리 확인
!pip freeze

In [ ]:
import subprocess

result = subprocess.run(['pip', 'freeze'], stdout=subprocess.PIPE)
installed_packages = result.stdout.decode('utf-8').split('\n')

# @ 기호 이후의 문자 제거, @가 없는 경우 그대로 유지
cleaned_packages = [package.split('@')[0].strip() if '@' in package else package.strip() for package in installed_packages]

# 정리된 결과 출력
for package in cleaned_packages:
    print(package)

# 연산자

In [177]:
# + : A+B 합
# - : A-B차
# * : 곱
# ** : 제곱
# / : 나누기
# // : 나누기의 몫
# % : 나누기의 나머지
# > : 크다
# < : 작다
# >= : 이상
# <= : 이하
# == : 같은 값
# != : 다른 값
# = : 할당
# := : A할당하고 B를 반환 한다.
# [0:1] 슬라이싱 : N : (M-1)까지 범위를 탐색
# [0] 인덱싱 : N번쨰 자리를 탐색

# iteration 관련 표준 함수

In [ ]:
iter() # 반복자를 리턴
reversed()
next() # 반복자가 가르키는 다음 값을 반환하고, 반복자는 다음 요소로 이동

# iterable (반복이 가능한) 타입
str, list, tuple, dict, set, range, dictionary(디렉토리)

In [43]:
# while문 활용

str_ = 'ABCD'

print("iter()")
iter_ = iter(str_)
n = 0
while n <= len(str_) :
    n += 1
    print(next(iter_, "StopIteration 에러 대신 리턴"))

print('-' * 50)

print("reversed()")
iter_ = reversed(str_)
n = 0
while n <= len(str_) :
    n += 1
    print(next(iter_, "StopIteration 에러 대신 리턴"))

print('-' * 50)

print("iter()")
iter_ = iter(str_)
try :
    while True :
        print(next(iter_))

except StopIteration :
    print("StopIteration 에러 발생")

print('-' * 50)

print("reversed()")
iter_ = reversed(str_)
try :
    while True :
        print(next(iter_))

except StopIteration :
    print("StopIteration 에러 발생")

iter()
A
B
C
D
StopIteration 에러 대신 리턴
--------------------------------------------------
reversed()
D
C
B
A
StopIteration 에러 대신 리턴
--------------------------------------------------
iter()
A
B
C
D
StopIteration 에러 발생
--------------------------------------------------
reversed()
D
C
B
A
StopIteration 에러 발생


In [49]:
# for문 활용

str_ = 'ABCD'

for i in str_ :
    print(i)
print('-' * 50)

for i in iter(str_) :
    print(i)
print('-' * 50)

for i in reversed(str_) :
    print(i)

A
B
C
D
--------------------------------------------------
A
B
C
D
--------------------------------------------------
D
C
B
A


# list

In [ ]:
list_name.append(A) # 'list_name'끝에 'A'를 그대로 추가
list_name.extend(iterable) # 'list_name'끝에 'iterable'의 모든 항목을 순차적으로 추가
list_name.insert(0, 'b') # 0 위치에 b 추가
list_name.count('a') # 리스트에 'a' 개수

In [47]:
list_1 = ['A', 'B', 'C', 'D', 'E']
list_2 = ['A', 'B', 'C', 'D', 'E']
list_3 = ['A', 'B', 'C', 'D', 'E']
list_4 = ['A', 'B', 'C', 'D', 'E']
list_ = ['가', '나', '다']
str_ = '가나다'

list_1.append(list_)
print(f"list.append (list) : {list_1}")

list_2.extend(list_)
print(f"list.extend (list) : {list_2}")

print('-' * 50)

list_3.append(str_)
print(f"list.append (str) : {list_3}")

list_4.extend(str_)
print(f"list.extend (str) : {list_4}")

list.append (list) : ['A', 'B', 'C', 'D', 'E', ['가', '나', '다']]
list.extend (list) : ['A', 'B', 'C', 'D', 'E', '가', '나', '다']
--------------------------------------------------
list.append (str) : ['A', 'B', 'C', 'D', 'E', '가나다']
list.extend (str) : ['A', 'B', 'C', 'D', 'E', '가', '나', '다']


In [175]:
list_ = [0, 1, 2, 3, 4]
insert_ = 3 # 원하는 자리 번호 입력
list_.insert(insert_, f"'{insert_}'자리에 추가")
print(list_)

[0, 1, 2, "'3'자리에 추가", 3, 4]


In [164]:
list_ = [0, 1, 2, 3, 4]
count = 1 # 개수를 확인하고 싶은거 입력
if type(count) == str :
    print(f"'{count}'(str)의 개수는 :", list_.count(count))
elif type(count) == int :
    print(f"'{count}'(int)의 개수는 :", list_.count(count))

'1'(int)의 개수는 : 1


# numpy

In [24]:
import numpy as np

# 넘파이 배열을 반복하여 새로운 배열을 생성
arr_1 = np.array([1, 2, 3]) # 반복할 배열
arr_2 = [1, 2, 3] # 리스트
repeats = 3 # 각 요소를 반복할 횟수를 나타내는 정수 또는 배열

# axis: 반복을 적용할 축, 기본값은 None, 배열을 평평하게 만듬
repeated_arr_1 = np.repeat(arr_1, repeats, axis = None)
repeated_arr_2 = np.repeat(arr_2[2], repeats, axis = None)
print(repeated_arr_1)
print(repeated_arr_2)

[1 1 1 2 2 2 3 3 3]
[3 3 3]


In [14]:
import numpy as np

# 넘파이 배열로 변환
arr_1 = [[1, 2, 3], [4, 5, 6]]
arr_2 = [1, 2, 3, 4, 5, 6]
print(np.array(arr_1))
print(np.array(arr_2))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [19]:
import numpy as np

# 넘파이 배열에 원소를 추가
arr = np.array([1, 2, 3]) # 값이 추가될 배열
values = np.array([[4, 5, 6], [7, 8, 9]]) # 추가될 값 또는 배열

# axis : 값이 추가될 축. 기본값은 None, 이 경우 값은 배열을 평탄화하고 값을 추가
new_arr = np.append(arr, values, axis = None)
print(new_arr)

[1 2 3 4 5 6 7 8 9]


In [29]:
import numpy as np

# 넘파이 배열의 형태를 변경
arr_1 = np.array([1, 2, 3, 4, 5, 6]) # 값이 추가될 배열
arr_2 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newshape_1 = (2, 3) # 변경된 형태를 나타내는 튜플(tuple) 또는 정수(int)의 리스트
newshape_2 = (2, 2, 3)
# order: 배열의 요소를 읽는 순서 ('C' 또는 'F'). 기본값은 'C'로, 행 기반(row-major) 순서
reshaped_arr_1 = np.reshape(arr_1, newshape_1, order = 'C')
reshaped_arr_2 = np.reshape(arr_2, newshape_2, order = 'C')
print(reshaped_arr_1)
print(reshaped_arr_2)

[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [30]:
import numpy as np

# 넘파이 배열 확인
arr = np.array([[1, 2, 3], [4, 5, 6]])
shape_arr = np.shape(arr)
print(shape_arr)

(2, 3)


# OS

In [ ]:
import os

os.getcwd() # 현재 프로세스의 작업 디렉토리 확인
os.path.exists('경로/확인힐이름') # 경로에 특정 파일이나 디렉토리의 존재 여부 확인
os.mkdir('경로' + '/디렉토리명') # 경로에 디렉토리를 생성
os.listdir('경로' + '/디렉토리명') # 지정된 경로의 디렉토리에 존재하는 파일 혹인 디렉토리 반환(리스트 형태)
os.walk() # 지정된 경로의 디렉토리를 순차적으로 탐색하여 반복문으로 활용
os.rename('경로/경로/원래 이름', '경로/경로/바꿀 이름') # 지정한 파일의 이름을 변경
os.makedirs() # 디렉토리 생성
os.remove() # 삭제

In [4]:
import os

check_dir = "경로"

for dirpath, dirnames, filenames in os.walk(check_dir) :
    print('-' * 100)
    print(f"현재 디렉토리 경로 : {dirpath}")
    print(f"하위 디렉토리 목록 : {dirnames}")
    print(f"현재 디렉토리 파일 목록 : {filename}")
    print('-' * 100)
    for dirname in dirnames:
        print(dirname)
    for file in filenames :
        filename, extension = os.path.split(file)

In [ ]:
import os

def cur_dir_1() -> None:
    """
    Input
        1) None
    Print
        1) 현재 작업 디렉토리
        2) 현재 디렉토리 내의 파일과 하위 디렉토리 목록 리스트
    Output
        1) dir_list (list) :
            현재 디렉토리 내의 파일과 하위 디렉토리 목록 리스트
    """
    # 현재 작업 디렉토리 확인
    cur_directory = os.getcwd()
    print('\n현재 작업 디렉토리 :\n', cur_directory)
    
    # 현재 디렉토리 내의 파일과 하위 디렉토리 목록 -> 리스트로 반환
    dir_list = os.listdir(cur_directory)
    print('\n현재 디렉토리 내의 파일과 하위 디렉토리 목록 :\n', dir_list)
    
    return dir_list

In [ ]:
import os

def cur_dir_2(directory_name : str):
    """
    Input
        1) directory_name (str) :
            현재 작업 디렉토리에서 확인하고 싶은 디렉토리 이름
    Print
        1) directory_name (str) 내의 파일과 하위 디렉토리 목록 리스트
    """
    # 현재 디렉토리에서 특정 디렉토리 내의 파일과 하위 디렉토리 목록 -> 리스트로 반환
    dir_listdir = os.path.join(os.getcwd(), directory_name)
    data_list = os.listdir(dir_listdir)
    print(f'\n{dir_listdir} 내의 파일과 하위 디렉토리 목록 :\n', data_list)
    
    return data_list

# pandas

In [ ]:
import os
import pandas as pd

def dir_csv_excel(directory_name : str, index_col : int or str = None, encoding : str = None):
    """
    Input
        1) directory_name (str) :
            현재 작업 디렉토리에서 cvs, excel 파일들을 불러올 디렉토리 이름
        2) index_col (int | str) = None :
            인덱스로 사용할 열의 번호 또는 이름을 지정
        3) encoding (str) = None :
            파일의 인코딩을 지정
            한글 파일 에러 : 'cp949'
            아스키 코드 에러 : 'ISO-8859-1'
    Output
        1) dataset (dict) :
            directory_name (str) 내의 csv, excel 파일,
            변수 = dir_csv_excel('directory_name')['파일이름.확장자']로 사용
    """
    # 현재 디렉토리에서 특정 디렉토리 내의 파일과 하위 디렉토리 목록 -> 리스트로 반환
    dir_listdir = os.path.join(os.getcwd(), directory_name)
    data_list = os.listdir(dir_listdir)
    print(f"\n'{dir_listdir}' 내의 파일과 하위 디렉토리 목록 :\n", data_list)

    # csv 파일 대량 불러오기 -> dict 형태로 반환
    dataset = dict()
    
    try:
        for data in data_list:
            if data.lower().endswith('.csv'): # csv 파일만
                print(data) # csv 파일들 출력
                dataset[data] = pd.read_csv(os.path.join(dir_listdir, data), index_col = index_col, encoding = encoding)
            
            elif data.lower().endswith('.xls') or data.lower().endswith('.xlsx'):
                print('/n', data) # excel 파일들 출력
                dataset[data] = pd.read_excel(os.path.join(dir_listdir, data), index_col = index_col)
    
    except Exception as e:
        print(e)
        
    return dataset

In [ ]:
import pandas as pd

# 파일 불러오기를 위한 함수
df이름 = pd.read_csv('경로/파일이름.csv', index_col = 0)
raw_data_1 = pd.read_csv('경로/파일이름.tsv', sep = '\t')
raw_data_2 = pd.read_excel('경로/파일이름.xlsx', index_col = 0)

# 불러오기 한글 파일 에러 : , encoding = 'cp949'
# 불러오기 아스키 코드 에러 : , encoding = 'ISO-8859-1'

In [ ]:
import pandas as pd

# 파일 내보내기를 위한 함수
df이름.to_csv('filename.csv')
df이름.to_csv('filename.csv', index = False)
df이름.to_csv('filename.tsv')
df이름.to_csv('filename.tsv', sep='\t')
df이름.to_excel('filename.xlsx')
df이름.to_excel('filename.xlsx', index = False)

##### 데이터 프레임 합치기

In [ ]:
# 중복제거 후 인덱스 리셋 후 기존 인덱스 칼럼 삭제
df이름.drop_duplicates().reset_index().drop(columns = 'index')

In [ ]:
# axis = 0 : 행 방향, axis = 1 : 열 방향
# join = 'outer' : 합집합, join = 'inner' : 교집합
# ignore_index = True : 인덱스 번호 재배열
concat_data = pd.concat([raw_data_1, raw_data_2], ignore_index = True)
concat_data = pd.concat([raw_data_1, raw_data_2], axis = 1, join = 'inner',
                        ignore_index = True)

In [ ]:
# how  = 'inner' : 교집합, how = 'outer' : 합집합'
# how  = 'left' : 왼쪽, how = 'right' : 오른쪽'
# left_on = '왼쪽 칼럼', right_on = '오른쪽 칼럼'
merge_data = raw_data_1.merge(raw_data_2, how = 'inner', on = '칼럼')
merge_data = pd.merge(raw_data_1, raw_data_2) # how = 'inner', on = 공통 열이름 
merge_data = pd.merge(raw_data_1,raw_data_2, how = 'outer',
                      left_on = ['칼럼'], right_on = ['칼럼'])
merge_data = pd.merge(raw_data_1, raw_data_2, how = 'left',
                      left_on = ['칼럼'], right_on = ['칼럼'])
merge_data = pd.merge(raw_data_1, raw_data_2, how = 'right',
                      left_on = ['칼럼'], right_on = ['칼럼'])

##### 데이터 프레임 확인

In [ ]:
def check_df(df):
    """
    Input
        1) df (DataFrame) :
            확인하고 싶은 데이터 프레임
    Print
        1) df (DataFrame)의 rows x columns
    display
        1) df (DataFrame)의 칼럼별(column)
        유니크의 개수(unique_cut), 비결측치의 개수(non_null_cut), 데이터 타입(dtype),
        결측치의 개수(null_cut), 결측치의 비율(null_ratio)
        2) df (DataFrame)의 칼럼중, 데이터 타입이 수치형인 칼럼들의 describe()
        데이터의 총 개수, 평균, 표준 편차, 최솟값, 25, 50, 75 백분위수, 최댓값
    """
    print('rows x columns :', df.shape) # (행 개수, 열 개수)
    # 칼럼별 unique 개수 확인
    columns_info = dict()
    columns = df.columns
    for col in columns:
        columns_info[col] = len(df[col].unique())
    data = [{'index': col, 'unique_cut': count} for col, count in columns_info.items()]
    unique_cut_df = pd.DataFrame(data)
    # unique_cut_df.set_index('index').T
    non_null_cut_df = pd.DataFrame(df.count()).rename(columns = {0 : 'non_null_cut'}).reset_index()# 칼럼별 비결측치 개수
    info_df = pd.DataFrame(df.dtypes).rename(columns = {0 : 'dtype'}).reset_index() # 데이터 프레임 info
    # 칼럼별 결측지 비율 확인
    null_cnt_df = pd.DataFrame(df.isnull().sum()).rename(columns = {0 : 'null_cut'}).reset_index()
    null_cnt_df['null_ratio'] = round(null_cnt_df['null_cut'] / len(df) * 100, 2)
    # 합치기
    unique_non_null_cut_df = pd.merge(unique_cut_df, non_null_cut_df)
    unique_non_null_info_cut_df = pd.merge(unique_non_null_cut_df, info_df)
    unique_non_null_info_null_cut_df = pd.merge(unique_non_null_info_cut_df, null_cnt_df).rename(columns = {'index' : 'column'})
    # describe - 통계
    int_float_cnt  = unique_non_null_info_null_cut_df[(unique_non_null_info_null_cut_df['dtype'] == 'int64') |
                     (unique_non_null_info_null_cut_df['dtype'] == 'float64')]
    # 보여주기
    if len(unique_non_null_info_null_cut_df.columns) >= len(int_float_cnt.columns):
        len_number = len(unique_non_null_info_null_cut_df.columns)
    else:
        len_number = len(int_float_cnt.columns)
    pd.set_option('display.max_columns', len_number)            
    display(unique_non_null_info_null_cut_df)
    display(df.describe())

In [ ]:
# 테이블 칼럼 타입 확인
df이름.info()

In [ ]:
# 테이블 수치형 칼럼 통계
df이름.describe()

In [ ]:
check_df = df이름
print('칼럼명 :', check_df.columns) # 칼럼명 확인
print('(rows, columns) :', check_df.shape) # (행 개수, 열 개수)
check_df.count() # 칼럼별 항목 개수 확인

In [ ]:
# 칼럼 unique별 개수 확인
df이름['칼럼명'].value_counts()

In [ ]:
# 머리와 꼬리 동시에 보기
display_df = df이름
display(display_df.head(3))
display(display_df.tail(3))

In [ ]:
# 두개의 데이터 머리만 동시에 보기
display(df이름.head(3), df이름.head(3))

In [ ]:
# 해당 수의 행, 열 만큼 보이게 하기
pd.set_option('display.max_rows', 숫자)
pd.set_option('display.max_columns', len(df이름.columns))

##### 칼럼별 unique 개수 확인

In [ ]:
# 칼럼별 unique 개수 확인
unique_check_df = df이름

columns_info = dict()
columns = unique_check_df.columns
for col in columns:
    columns_info[col] = len(unique_check_df[col].unique())

columns_info

In [ ]:
# 칼럼별 unique 개수 확인
unique_check_df = df이름

columns_info = dict()
columns = check_df.columns
for col in columns:
    columns_info[col] = len(check_df[col].unique())
data = [{'columns': col, 'unique_count': count} for col, count in columns_info.items()]
unique_count_df = pd.DataFrame(data)
unique_count_df

##### 칼럼 타입 변경

In [ ]:
# 칼럼 타입 변경
df이름 = df이름.astype({'칼럼명' : 'object', 
                    '칼럼명' : 'int64',
                    '칼럼명' : 'float64',
                    '칼럼명' : 'bool',
                    '칼럼명' : 'datetime64[ns]'})
df이름.info()

##### 칼럼 값(values) 변경

In [ ]:
# 칼럼 값(values) 변경
def change_value(values) :
    if values == '기존' :
        return '변경'
    elif values == '기존' :
        return '변경'

df이름['칼럼명'] = df이름['칼럼명'].apply(change_value)

In [ ]:
df이름['칼럼명'] = df이름['칼럼명'].map({'기존' : '변경', '기존' : '변경'})

##### 띄어쓰기 기준으로 칼럼 내용 내눠서 각 칼럼으로 저장

In [ ]:
# 띄어쓰기 기준으로 칼럼 내용 내눠서 각 칼럼으로 저장
df이름['새칼럼명'] = df이름['기존칼럼명'].apply(
    lambda x: x.split(' ')[0][ : ])

df이름['새칼럼명'] = df이름['기존칼럼명'].apply(
    lambda x: x.split(' ')[1][ : ])

pd.set_option('display.max_columns', len(df이름.columns))
df이름.head(3)

##### 칼럼명 변경

In [ ]:
# 단일 칼럼명 변경
df이름 = df이름.rename(columns = {'칼럼명' : '변경명'})

# 복수 칼럼명 변경
df이름 = df이름.rename(columns = {'칼럼명' : '변경명',
                              '칼럼명' : '변경명',
                              '칼럼명' : '변경명',
                              '칼럼명' : '변경명',
                              '칼럼명' : '변경명',
                              '칼럼명' : '변경명',
                              '칼럼명' : '변경명',
                              '칼럼명' : '변경명',
                              '칼럼명' : '변경명',
                              '칼럼명' : '변경명',
                              '칼럼명' : '변경명',
                              '칼럼명' : '변경명'})

In [ ]:
# 칼럼명 지정 문자 바꾸기
df이름 = df이름.columns.str.replace('기존_문자', '바꿀_문자')

In [ ]:
# 칼럼명 지정 문자 추가
df이름.add_prefix('추가_문자') # 칼럼명 앞에 추가
df이름.add_suffix('추가_문자') # 칼럼명 뒤에 추가

##### 행, 열의 순서 변경, 삽입, 삭제

In [ ]:
# 칼럼 순서 변경
df이름 = df이름[['칼럼명', '칼럼명', ..., '칼럼명']]

In [ ]:
# 칼럼 삽입 ==, >, <, !=
df이름['새칼럼명'] = 값
df이름['새칼럼명'] = df이름['기존칼럼명'] + df이름['기존칼럼명']

In [ ]:
# 단일 칼럼 삭제
df이름 = df이름.drop(columns = '삭제할칼럼명')
df이름 = df이름.drop('삭제할칼럼명', axis = 1)
del df이름['삭제할칼럼명']

# 복수 칼럼 삭제
df이름 = df이름.drop(['삭제할칼럼명', '삭제할칼럼명'], axis = 1)
del df이름['삭제할칼럼명'], df이름['삭제할칼럼명']

In [ ]:
# 중복제거 후 인덱스 리셋 후 기존 인덱스 칼럼 삭제
df이름.drop_duplicates().reset_index().drop(columns = 'index')

In [ ]:
# 로우(행) 삭제
df이름.drop(index = '인덱스_번호')

In [ ]:
df이름 = df이름.sort_values(by = ['칼럼명']) # 오름차순
df이름 = df이름.sort_values(by = ['칼럼명'], ascending = False) # 내림차순

##### 필터링

In [ ]:
# 필터링 ==, >, <, !=
df이름[df이름['칼럼명'] == 값] # 전일치 검색
df이름[(df이름['칼럼명'] == 값) & (df이름['칼럼명'] == 값)] # 복합조건
df이름[(df이름['칼럼명'] == 값) | (df이름['칼럼명'] == 값)] # 복합조건
df이름[df이름['칼럼명'].apply(lambda x : x.startswith(값))] # 머릿말 검색
df이름[df이름['칼럼명'].apply(lambda x : x.endswith(값))] # 꼬릿말 검색
df이름[df이름['칼럼명'].isin([값, 값, 값])] # 내용을 포함하는지

In [ ]:
# 내용을 포함하는지
target = [값, 값, 값]
df이름[df이름['칼럼명'].apply(lambda x : x in target)]

##### 칼럼, 인덱스 목록 리스트로 반환

In [ ]:
# 칼럼, 인덱스 목록 리스트로 반환
list(df이름.columns) # 칼럼
df이름.columns.tolist() # 칼럼
list(df이름.columns.values) # 칼럼

list(df이름.index) # 인덱스
df이름.index.tolist() # 인덱스
list(df이름.index.values) # 인덱스

##### 모든 열을 행으로 이동시키기

In [ ]:
# 모든 열을 행으로 이동시키기
df이름.T
pd.melt(df이름, id_vars = ['A'], value_vars = ['B']) # 데이터프레임의 A열은 그대로 두고, B열만 행으로 이동
pd.melt(df이름, id_vars = ['A'], value_vars = ['B', 'C']) # A열만 그대로, B열과 C열은 행으로 이동
df이름.pivot(index = 'A', columns = 'B', values = 'C') # A열을 새로운 인덱스로 만들고, B열 데이터는 새로운 열로 만들며, C열이 그 안의 데이터가 되도록 설정
df이름.reset_index() # 인덱스를 리셋
df이름.columns.name = None

##### 피봇 테이블

In [ ]:
# 피봇 테이블
pd.pivot_table(df이름, index = ['칼럼명', '칼럼명']) # 기본
pd.pivot_table(df이름, index = ['칼럼명','칼럼명'],
               values = ['칼럼명', '칼럼명'], # 원하는 칼럼
               columns = ['거래처'], # 원하는 칼럼
               aggfunc = ['산식', '산식'], # 원하는 산식
               fill_value = 0, # nan값 0으로
               margins = True) # 오른쪽 끝에 총계 추가

# 피봇 테이블 필터링
pivot_table명.query("인덱스명 == ['인덱스값', '인덱스값']")

##### groupby

In [ ]:
groupby_df이름 = data.groupby(by = '칼럼명')
groupby_df이름.size()

In [ ]:
# groupby 하나의 계산
# df이름.groupby('그룹칼럼1')['집계칼럼'].집계함수() : A칼럼 그룹의 B칼럼값을 집계함수
groupby_df이름 = df이름.groupby('그룹칼럼')['집계칼럼'].mean() # 평균
groupby_df이름 = df이름.groupby('그룹칼럼')['집계칼럼'].median() # 중위수
groupby_df이름 = df이름.groupby('그룹칼럼')['집계칼럼'].count() # 개수
groupby_df이름 = df이름.groupby('그룹칼럼')['집계칼럼'].sum() # 합산
groupby_df이름 = df이름.groupby('그룹칼럼')['집계칼럼'].min() # 최소
groupby_df이름 = df이름.groupby('그룹칼럼')['집계칼럼'].max() # 최대
groupby_df이름 = df이름.groupby('그룹칼럼')['집계칼럼'].std() # 표준편차
groupby_df이름 = df이름.groupby('그룹칼럼')['집계칼럼'].var() # 분산
groupby_df이름 = df이름.groupby('그룹칼럼')['집계칼럼'].quantile() # 특정 백분위
groupby_df이름 = df이름.groupby('그룹칼럼')['집계칼럼'].describe() # 전반적인 지표
groupby_df이름 = df이름.groupby(['A칼럼1', 'A칼럼2'])['B칼럼'].집계함수()

In [ ]:
groupby_df이름 = pd.DataFrame(df이름.groupby('그룹칼럼1')['집계칼럼'].count()).reset_index()
groupby_df이름 = groupby_df이름.rename(columns = {'기존칼럼명' : '바꿀칼럼명', '기존칼럼명' : '바꿀칼럼명'})
groupby_df이름

In [ ]:
# groupby 복수의 계산
groupby_df이름 = df이름.groupby(['A칼럼1','A칼럼2']).agg(
    {'계산할컬럼명1' : 집계함수1(),
     '계산할컬럼명2' : 집계함수2(),
     '계산할컬럼명3' : 집계함수3()}
    )

In [ ]:
# groupby 복수의 계산
groupby_df이름 = pd.DataFrame(
    {'새로운컬럼명1' : df이름.groupby(['A칼럼1','A칼럼2'])['집계칼럼'].집계함수1(),
     '새로운컬럼명2' : df이름.groupby(['A칼럼1','A칼럼2'])['집계칼럼'].집계함수2(),
     '새로운컬럼명3' : df이름.groupby(['A칼럼1','A칼럼2'])['집계칼럼'].집계함수3()}
   )

##### 기타 기능

In [ ]:
# 시작 날짜 부터 입력한 개수 만큼 뒤로 날짜를 생성함
pd.date_range('2001-01-01(시작할 날짜)', periods = '개수')

##### 결측치

#####  머신러닝 및 데이터 분석에서 상황과 목적에 맞게 처리해야 하는 중요한 프로세스 중 하나



1. 결측치 비율이 10% 미만인 경우
- 삭제 가능
<p>


2. 결측치 비율이 30% ~ 50%인 경우
- 삭제 위험
<p>


3. 결측치 비율이 50% 이상인 경우
- 데이터 자체에 대한 추가 검증 필요 or 해당 컬럼의 제거 고려
<p> 
    
==============================
##### * 결측치를 처리하는 방법은 다양
    
1. 제거
- 한개 이상의 결측치가 있는 모든 행 제거
    
2. 대치
- 결측치를 특정값(평균, 최소, 최대, 최반값 등등)으로 대체
    
3. 보간법
- 추세를 결측치 이외의 값들을 선형적으로 같은 간격으로 처리 (시계열 데이터에 적합)

In [ ]:
# 칼럼별 결측지 비율 확인
null_check_df = df이름
null_cnt_df = pd.DataFrame(null_check_df.isnull().sum()).rename(columns = {0 : 'null_count'}).reset_index()
null_cnt_df['null_ratio'] = round(null_cnt_df['null_count'] / len(null_check_df) * 100, 2)
null_cnt_df = null_cnt_df.rename(columns = {'index' : 'columns'})
null_cnt_df

In [ ]:
def null_cnt(null_check_df):
    """
    Input
        1) null_check_df (DataFrame) :
            확인하고 싶은 데이터 프레임

    Output
        1) null_cnt_df (DataFrame)의 칼럼별(column) 결측치의 개수(null_cut)
    """
    null_cnt_df = pd.DataFrame(null_check_df.isnull().sum()).rename(columns = {0 : 'null_count'}).reset_index()
    null_cnt_df['null_ratio'] = round(null_cnt_df['null_count'] / len(null_check_df) * 100, 2)
    null_cnt_df = null_cnt_df.rename(columns = {'index' : 'columns'})
    
    return null_cnt_df

In [ ]:
def check_df(df):
    """
    Input
        1) df (DataFrame) :
            확인하고 싶은 데이터 프레임
    Print
        1) df (DataFrame)의 rows x columns
    display
        1) df (DataFrame)의 칼럼별(column)
        유니크의 개수(unique_cut), 비결측치의 개수(non_null_cut), 데이터 타입(dtype),
        결측치의 개수(null_cut), 결측치의 비율(null_ratio)
        2) df (DataFrame)의 칼럼중, 데이터 타입이 수치형인 칼럼들의 describe()
        데이터의 총 개수, 평균, 표준 편차, 최솟값, 25, 50, 75 백분위수, 최댓값
    """
    print('rows x columns :', df.shape) # (행 개수, 열 개수)
    # 칼럼별 unique 개수 확인
    columns_info = dict()
    columns = df.columns
    for col in columns:
        columns_info[col] = len(df[col].unique())
    data = [{'index': col, 'unique_cut': count} for col, count in columns_info.items()]
    unique_cut_df = pd.DataFrame(data)
    # unique_cut_df.set_index('index').T
    non_null_cut_df = pd.DataFrame(df.count()).rename(columns = {0 : 'non_null_cut'}).reset_index()# 칼럼별 비결측치 개수
    info_df = pd.DataFrame(df.dtypes).rename(columns = {0 : 'dtype'}).reset_index() # 데이터 프레임 info
    # 칼럼별 결측지 비율 확인
    null_cnt_df = pd.DataFrame(df.isnull().sum()).rename(columns = {0 : 'null_cut'}).reset_index()
    null_cnt_df['null_ratio'] = round(null_cnt_df['null_cut'] / len(df) * 100, 2)
    # 합치기
    unique_non_null_cut_df = pd.merge(unique_cut_df, non_null_cut_df)
    unique_non_null_info_cut_df = pd.merge(unique_non_null_cut_df, info_df)
    unique_non_null_info_null_cut_df = pd.merge(unique_non_null_info_cut_df, null_cnt_df).rename(columns = {'index' : 'column'})
    # describe - 통계
    int_float_cnt  = unique_non_null_info_null_cut_df[(unique_non_null_info_null_cut_df['dtype'] == 'int64') |
                     (unique_non_null_info_null_cut_df['dtype'] == 'float64')]
    # 보여주기
    if len(unique_non_null_info_null_cut_df.columns) >= len(int_float_cnt.columns):
        len_number = len(unique_non_null_info_null_cut_df.columns)
    else:
        len_number = len(int_float_cnt.columns)
    pd.set_option('display.max_columns', len_number)            
    display(unique_non_null_info_null_cut_df)
    display(df.describe())

In [ ]:
# 결측치 유무 확인
df이름['칼럼명'].isna().unique()

In [ ]:
# 결측치 처리
df이름 = df이름.fillna('A') # 대상 전체의 nan값을 A로 변경
df이름 = df이름.fillna(df이름.mean()) # 대상 전체의 nan값을 평균으로 변경
df이름 = df이름.dropna(axis = 0, subset = ['칼럼명']) # axis = 0 행방향




In [ ]:
# 단일 칼럼 삭제
df이름 = df이름.drop(columns = '삭제할칼럼명')
df이름 = df이름.drop('삭제할칼럼명', axis = 1)
del df이름['삭제할칼럼명']

# 복수 칼럼 삭제
df이름 = df이름.drop(['삭제할칼럼명', '삭제할칼럼명'], axis = 1)
del df이름['삭제할칼럼명'], df이름['삭제할칼럼명']

In [ ]:
# 해당 칼럼의 값과 일치하는 인덱스 번호
df이름.index[df이름['칼럼명'] == 값].tolist()[칼럼 순서 위치]

# 해당 인덱스 번호와 일치하는 칼럼의 값
df이름.loc[인덱스번호].tolist()[칼럼 순서 위치]

# 다음거